/**
 * Expense Tracker
 * This is the API routes for Expense Tracker
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExpenseDetails } from './expenseDetails';

export interface GetExpenseResponse { 
    expenses?: Array<ExpenseDetails>;
    isPremium?: boolean;
    totalExpenses?: number;
    hasNextPage?: boolean;
    hasPreviousPage?: boolean;
    nextPage?: number;
    currentPage?: number;
    previousPage?: number;
    lastPage?: number;
}