/**
 * Expense Tracker
 * This is the API routes for Expense Tracker
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserDetails { 
    _id?: string;
    username?: string;
    email?: string;
    password?: string;
    isPremium?: boolean;
}